### ISSUE TITLE
ERROR:STATION_ID

### ISSUE THREAD

**Issue by degupukas** [synapsemx/adsb-stats-twitter#5]
hello
 I have installed all the dependencies I have also created the .env file and I have the following error

Can somebody help me

WARN: RUN_MODE not equal to 'live' so this won't post to Twitter
/home/gael/adsb-stats-twitter/main.js:17
   throw new Error('STATION_ID must be defined');
   ^

Error: STATION_ID must be defined
    at Object.<anonymous> (/home/gael/adsb-stats-twitter/main.js:17:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by sacarino** [comment]
hey @degupukas 👋

Sounds like maybe it can't find the `.env`? Did you create it in the same path as the `main.js` file?
